server:
  port: 8081

spring:
  redis:
    # Redis服务器地址
    host: 124.221.128.48
#    host: localhost
    # Redis服务器端口号下
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: "123456"
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
keycloak:
  # keycloak的地址
  auth-server-url: http://124.221.128.48:8180
  # keycloak中的realm
  realm: webchat
  # client ID
  resource: webchat-bs
  credentials:
    secret: Vdfo7TNuYUJhWKssCvoEJWXzcTIoffg7
  ssl-required: none
  use-resource-role-mappings: true
  cors: true
  bearer-only: false
  principal-attribute: preferred_username
  securityConstraints:
    - authRoles:
        - user
      securityCollections:
        # name可以随便写
        - name: common user
          patterns:
            - /webchat/login


